version: '3.9'

services:
  mysql:
    build: ./docker
    image: planetscale-data
    container_name: planetscale-data
    # platform: linux/arm64
    environment:
      MYSQL_DATABASE: planetscale_dev
      MYSQL_USER: planetscale
      MYSQL_PASSWORD: planetscale
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d # 初期データ投入
      - ./docker/init/my.cnf:/etc/mysql/conf.d/my.cnf
      - planetscale-data:/var/lib/mysql
    ports:
      - '33306:3306'
    restart: always

volumes:
  planetscale-data:
    driver: local
